import type { Metadata } from "next";
import Link from "next/link";
import { SampleQr } from "@/components/sample-qr";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { SITE_NAME, SITE_URL } from "@/lib/site";

export const metadata: Metadata = {
  title:
    "actuallyfreeqr — Free QR code generator. No sign-up, no email, no tracking.",
  description:
    "Make a QR code for free in about ten seconds. No sign-up, no email, no account, no tracking, no watermark and no expiry. Type a name and a link, then share, print or bookmark the code forever.",
  alternates: { canonical: "/" },
};

const PROMISES = [
  "No sign-up",
  "No email",
  "No account",
  "No tracking",
  "No watermark",
  "No expiry",
  "No limits",
  "No payment",
];

const FAQ = [
  {
    q: "Is it really free? What is the catch?",
    a: "It is really free, and there is no catch. There is no paid tier, no trial, no credit card and no upsell. The whole site is a few static files, so it costs almost nothing to run — charging you would be more work than giving it away.",
  },
  {
    q: "Do I have to make an account or give you my email?",
    a: "No. There is no sign-up form anywhere on this site, and no field asking for your email. Type a name and a link and you are done.",
  },
  {
    q: "Do the QR codes expire?",
    a: "Never. Your code contains your link directly, so it does not depend on this website staying online. If this site disappeared tomorrow, every QR code it ever made would keep working exactly as before.",
  },
  {
    q: "Do you track scans?",
    a: "We cannot, and that is deliberate. Scanning your code sends the phone straight to your link without passing through us, so there is no scan counter, no analytics dashboard and no log of who scanned what. There is no data because none is ever collected.",
  },
  {
    q: "How do I share a QR code with other people?",
    a: "Two ways, and both work. Download the image and send it around, or copy the page link — the entire code lives in that link, so anyone who opens it sees the same QR code. Handy when several people at an event need the same code on screen.",
  },
  {
    q: "Can I print it on a poster?",
    a: "Yes. The code is drawn as vector graphics, so it stays sharp at any size, and the downloaded image is high resolution. Printing the page directly gives you a clean, ready-to-pin sheet with the name on top.",
  },
  {
    q: "What can a QR code hold besides a link?",
    a: "Anything text-shaped. A link opens in the phone's browser, a WhatsApp code opens a chat with your number, a phone number offers to call it, a contact card offers to save itself to the address book, and plain text is simply shown. All five are built into the form.",
  },
  {
    q: "Where is my data stored?",
    a: "Nowhere. The QR code is generated by your own browser, and the only copy of it is the link in your address bar and whatever image you choose to download. There is no database on our side to store it in.",
  },
];

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebApplication",
      name: SITE_NAME,
      url: SITE_URL,
      applicationCategory: "UtilitiesApplication",
      operatingSystem: "Any browser",
      description:
        "A free QR code generator that needs no sign-up, no email and no account, and that does not track anyone.",
      isAccessibleForFree: true,
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
        availability: "https://schema.org/InStock",
      },
    },
    {
      "@type": "FAQPage",
      mainEntity: FAQ.map((item) => ({
        "@type": "Question",
        name: item.q,
        acceptedAnswer: { "@type": "Answer", text: item.a },
      })),
    },
  ],
};

export default function HomePage() {
  return (
    <>
      <script
        type="application/ld+json"
        // Static, hand-written object — nothing user supplied goes in here.
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <div className="shell">
        <SiteHeader />

        <main>
          <section className="hero">
            <div>
              <p className="eyebrow">Free forever · no account</p>
              <h1>
                QR codes that are <mark>actually free</mark>.
              </h1>
              <p className="lede">
                Type a name and a link. Get a QR code you can share, print and
                bookmark. No sign-up, no email, no tracking, no expiry date.
              </p>
              <div className="hero-actions">
                <Link href="/create" className="btn btn-lg">
                  Make a QR code
                </Link>
                <Link href="#how" className="btn btn-lg btn-ghost">
                  How it works
                </Link>
              </div>
              <p className="micro">
                Takes about ten seconds. Nothing leaves your browser.
              </p>
            </div>
            <SampleQr value={SITE_URL} />
          </section>
        </main>
      </div>

      <div className="band">
        <div className="shell">
          <ul className="promises">
            {PROMISES.map((promise) => {
              const [first, ...rest] = promise.split(" ");
              return (
                <li key={promise}>
                  <span>{first}</span>
                  {rest.join(" ")}
                </li>
              );
            })}
          </ul>
        </div>
      </div>

      <div className="shell">
        <section className="section" id="how">
          <h2 className="section-title">Three fields and you are done.</h2>
          <p className="section-lede">
            There is no dashboard to learn and no settings to get wrong. The
            form is the whole product.
          </p>
          <ol className="steps">
            <li className="step">
              <span className="step-num">1</span>
              <h3>Name it</h3>
              <p>
                Whatever you type appears above the code, so people know what
                they are pointing their camera at.
              </p>
            </li>
            <li className="step">
              <span className="step-num">2</span>
              <h3>Paste your link</h3>
              <p>
                Or a WhatsApp chat, a number to call, a contact card or any
                text. The code is drawn in your browser while you type.
              </p>
            </li>
            <li className="step">
              <span className="step-num">3</span>
              <h3>Share it</h3>
              <p>
                Download the image, print the page, or send the link — everyone
                who opens it sees the same code.
              </p>
            </li>
          </ol>
        </section>

        <section className="section" id="why">
          <h2 className="section-title">Why these codes outlive us.</h2>
          <p className="section-lede">
            Most &ldquo;free&rdquo; QR generators point the code at their own
            domain and forward the scan to you. That is the part they can later
            charge for, meter, or switch off. We do not do that.
          </p>
          <div className="split">
            <div className="note">
              <h3>Your link, not our redirect</h3>
              <p>
                The code contains your address and nothing else. A phone reads
                it and goes straight there — this website is not involved in the
                scan at all.
              </p>
            </div>
            <div className="note">
              <h3>No tracking, by construction</h3>
              <p>
                Since scans never touch our servers, there is no scan count, no
                analytics and no log. Not a policy we could quietly change: a
                fact about how it works.
              </p>
            </div>
            <div className="note">
              <h3>Printed today, working in ten years</h3>
              <p>
                If this site vanishes, every code it made keeps working. Nothing
                you make here can be held hostage later.
              </p>
            </div>
            <div className="note">
              <h3>The link is the code</h3>
              <p>
                Your QR page carries the whole code in its address. Bookmark it,
                message it to a colleague, put it on a slide — it renders the
                same for everyone.
              </p>
            </div>
          </div>
        </section>

        <section className="section" id="faq">
          <h2 className="section-title">Questions people reasonably ask.</h2>
          <div className="faq">
            {FAQ.map((item) => (
              <details key={item.q}>
                <summary>{item.q}</summary>
                <p>{item.a}</p>
              </details>
            ))}
          </div>
        </section>

        <section className="section" style={{ paddingTop: 0 }}>
          <h2 className="section-title">Ready when you are.</h2>
          <p className="section-lede">
            No form to fill in first. No email to confirm. Just the thing you
            came for.
          </p>
          <p style={{ marginTop: 32 }}>
            <Link href="/create" className="btn btn-lg btn-accent">
              Make a QR code
            </Link>
          </p>
        </section>

        <SiteFooter />
      </div>
    </>
  );
}
